"""
Makes the __init__.py file that pulls together the generated types
into the exceltypes package.
"""
import sys
import os
import re


def main():
    gen_py_path = os.path.join(os.path.dirname(__file__), "..", "exceltypes", "gen_py")
    output_path = os.path.join(os.path.dirname(__file__), "..", "exceltypes", "__init__.py")
    with open(output_path, "wt") as out_fh:
        print(f"# Auto-generated by {__file__}", file=out_fh)
        for file in os.listdir(gen_py_path):
            filepath = os.path.join(gen_py_path, file)
            name, ext = os.path.splitext(file)
            if os.path.isfile(filepath) and ext == ".py" and file != "__init__.py":
                print(f"from .gen_py.{name} import (", file=out_fh)
                with open(filepath, "rt") as fh:
                    classes = []
                    for line in fh.readlines():
                        match = re.match("class\s+(\w+).*", line)
                        if match:
                            classes.append(match.group(1))
                print(",\n".join(["    " + cls for cls in classes]), file=out_fh)
                print(")\n", file=out_fh)


if __name__ == "__main__":
    sys.exit(main())
